version: '3.4'

services:
  ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
    depends_on:
        - microserviciogastos
        - microservicioingresos

  microserviciogastos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4000:80"

  microservicioingresos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
