version: '3.4'

services:
  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile

  microserviciogastos:
    image: ${DOCKER_REGISTRY-}microserviciogastos
    build:
      context: .
      dockerfile: microServicioGastos/Dockerfile
    depends_on:
      - mongo
    networks:
      mynetwork:
        ipv4_address: 178.25.0.3
  
  microservicioingresos:
    image: ${DOCKER_REGISTRY-}microservicioingresos
    build:
      context: .
      dockerfile: microServicioIngresos/Dockerfile

  mongo:
    image: mongo:latest
    networks:
      mynetwork:
        ipv4_address: 178.25.0.2

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 178.25.0.0/24
