version: '3.4'

services:
  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile

  microserviciogastos:
    image: ${DOCKER_REGISTRY-}microserviciogastos
    build:
      context: .
      dockerfile: microServicioGastos/Dockerfile
  
  microservicioingresos:
    image: ${DOCKER_REGISTRY-}microservicioingresos
    build:
      context: .
      dockerfile: microServicioIngresos/Dockerfile
  
  microservicioreporte:
    image: ${DOCKER_REGISTRY-}microservicioreporte
    build:
      context: .
      dockerfile: microServicioReporte/Dockerfile



  

